version: 2.1

executors:
  macos_executor:
    macos:
      xcode: "15.3.0"

jobs:
  run_unit_tests:
    executor: macos_executor
    steps:
      - checkout
      
      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install CocoaPods
          command: sudo gem install cocoapods

      - run:
          name: Install Pods
          command: pod install --repo-update

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Run Unit Tests
          command: bundle exec fastlane ios unit_tests --verbose

      - run:
          name: Create Test Results Directory
          command: mkdir -p output/test_results

      - persist_to_workspace:
          root: .
          paths:
            - output/test_results

      - store_artifacts:
          path: output/test_results
          destination: test_results
  
  build_unsigned_xcarchive:
    executor: macos_executor
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler
      
      - run:
          name: Install CocoaPods
          command: sudo gem install cocoapods

      - run:
          name: Install Pods
          command: pod install --repo-update

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Build Unsigned xcarchive
          command: bundle exec fastlane ios build_unsigned_xcarchive --verbose

      - persist_to_workspace:
          root: .
          paths:
            - output/archive

      - store_artifacts:
          path: output/archive
          destination: archive

  create_unsigned_ipa:
    executor: macos_executor
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Install CocoaPods
          command: sudo gem install cocoapods

      - run:
          name: Install Pods
          command: pod install --repo-update

      - run:
          name: Generate unsigned ipa
          command: ./generate_unsigned_ipa.sh

      - store_artifacts:
          path: output/ipa
          destination: ipa

workflows:
  version: 2.1
  build:
    jobs:
      - run_unit_tests
      - build_unsigned_xcarchive:
          requires:
            - run_unit_tests
      - create_unsigned_ipa:
          requires:
            - build_unsigned_xcarchive
