version: 2.1

executors:
  macos_executor:
    macos:
      xcode: "15.3.0"

jobs:
  build_unsigned_xcarchive:
    executor: macos_executor
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Dependencies
          command: bundle install

      # - run:
      #     name: Set Deployment Target
      #     command: /usr/libexec/PlistBuddy -c "Set :IPHONEOS_DEPLOYMENT_TARGET 12.0" "StudyOn/Info.plist"

      - run:
          name: Build Unsigned xcarchive
          command: bundle exec fastlane ios build_unsigned --verbose

      - persist_to_workspace:
          root: .
          paths:
            - output/archive

      - run:
          name: Install curl_PROJ
          command: brew install curl

      - run:
          name: Upload xcarchive to GitLab
          command: |
            curl --request POST --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" \
              --form "file=@output/archive/StudyOn.xcarchive" \
              "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/uploads"

workflows:
  version: 2.1
  build:
    jobs:
      - build_unsigned_xcarchive
