version: 2.1

jobs:
  build_unsigned_ipa:
    macos:
      xcode: "15.3.0"

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Build Unsigned IPA
          command: bundle exec fastlane ios build_unsigned

      - persist_to_workspace:
          root: .
          paths:
            - output/ipa

workflows:
  version: 2.1
  build:
    jobs:
      - build_unsigned_ipa
