version: 2.1

executors:
  macos_executor:
    macos:
      xcode: "15.3.0"

jobs:
  build_unsigned_xcarchive:
    executor: macos_executor
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Dependencies
          command: bundle install

      # - run:
      #     name: Set Deployment Target
      #     command: /usr/libexec/PlistBuddy -c "Set :IPHONEOS_DEPLOYMENT_TARGET 12.0" "StudyOn/Info.plist"

      - run:
          name: Build Unsigned xcarchive
          command: bundle exec fastlane ios build_unsigned --verbose
      
      - run:
          name: Create Unsigned IPA
          command: bundle exec fastlane ios create_unsigned_ipa --verbose

      - persist_to_workspace:
          root: .
          paths:
            - output/archive
            - output/ipa

      - store_artifacts:
          path: output/archive
          detination: archive

      - store_artifacts:
          path: output/ipa
          destination: ipa

workflows:
  version: 2.1
  build:
    jobs:
      - build_unsigned_xcarchive
